name: Release to AUR

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - epy.py
      - tests/**
      - epy_extras/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate PKGBUILD
        run: |
          mkdir -p ./tmp
          bash build/gen_pkgbuild.sh > ./tmp/PKGBUILD
          cat ./tmp/PKGBUILD
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: epy-git
          pkgbuild: ./tmp/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
